name: PHP Composer

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Deploy to server
      run: ssh administrator@185.229.91.103 'cd /var/www/html/ci-cd-testing && git pull'
      env:
        FMP_LIVE: ${{ secrets.SSH_PRIVATE_KEY }}
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
